// src/components/FormItem.vue
<template>
	<div class="FormItem">
		<label
			v-if="$slots.label || label"
			class="FormItem__label"
			:for="labelFor"
		>
			<slot name="label">
				{{ label }}
			</slot>
		</label>

		<slot />

		<FormError
			v-if="!!error"
			class="FormItem__error"
			:text="error"
		/>

		<div
			class="FormItem__description"
			v-if="!!$slots.description || !!description"
		>
			<slot name="description">
				{{ description }}
			</slot>
		</div>
	</div>
</template>

<script>
	import FormError from './FormError.vue';

	export default {
		components: {
			FormError,
		},
		props: {
			label: {
				type: String,
			},
			labelFor: {
				type: [String, Number],
			},
			description: {
				type: String,
			},
			error: {
				type: String,
			},
		},
	};
</script>

<style lang="scss">
	.FormItem + .FormItem {
		margin-top: 15px;
	}

	.FormItem__label {
		display: block;
		margin-bottom: 5px;

		&[for] {
			cursor: pointer;
		}
	}

	.FormItem__description {
		color: #333;
		font-size: 15px;
		font-style: italic;
	}

	.FormItem__description,
	.FormItem__error {
		margin-top: 5px;
	}
</style>

// src/components/form/FormItem.svelte
<script lang="ts">
	export let description: string = '';
	export let error: string = '';
	export let label: string = '';
	export let labelFor: string = '';
</script>

<div>
	{#if label}
		<label for={labelFor}>
			{label}
		</label>
	{/if}

	<slot></slot>

	{#if description}
		<p class="description">{description}</p>
	{/if}

	{#if error}
		<p class="error">{description}</p>
	{/if}
</div>

<style lang="scss">
	div {
		margin-bottom: 10px;
	}

	label {
		display: block;
		margin-bottom: 5px;

		&[for] {
			cursor: pointer;
		}
	}

	.description {
		color: #333;
		font-size: 15px;
		font-style: italic;
	}

	.description,
	.error {
		margin-top: 5px;
	}
</style>
