// src/components/BookmarkForm.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";
	import type { Bookmark } from "./../store/bookmarks.js";
	import unique from "./../utils/unique.js";
	import TagInput from "./TagInput.svelte";
	import FormItem from "./form/FormItem.svelte";
	import InputText from "./form/InputText.svelte";
	import TextArea from "./form/TextArea.svelte";
	import Checkbox from "./form/Checkbox.svelte";
	import Button from "./Button.svelte";

	export let url = "";
	export let title = "";
	export let notes = "";
	export let tags = [];
	export let isFavorite = false;
	export let isToRead = false;
	export let isArchived = false;
	export let canDelete = false;

	const dispatch = createEventDispatcher<{
		save: Partial<Bookmark>;
		delete: undefined;
		cancel: undefined;
	}>();

	function handleSubmitForm() {
		dispatch("save", {
			title,
			url,
			tags: unique(tags),
			notes,
			isFavorite,
			isToRead,
			isArchived,
		});
	}

	function handleClickCancel() {
		dispatch("cancel");
	}

	function handleClickDelete() {
		dispatch("delete");
	}
</script>

<h2>Bookmark</h2>

<form on:submit|preventDefault={handleSubmitForm}>
	<FormItem label="Link" labelFor="bookmarkUrl">
		<InputText bind:value={url} type="url" id="bookmarkUrl" />
	</FormItem>

	<FormItem label="Title" labelFor="bookmarkTitle">
		<InputText bind:value={title} type="text" id="bookmarkTitle" />
	</FormItem>

	<FormItem label="Notes" labelFor="bookmarkNotes">
		<TextArea bind:value={notes} id="bookmarkNotes" />
	</FormItem>

	<FormItem label="Tags" labelFor="bookmarkTags">
		<TagInput bind:tags id="bookmarkTags" />
	</FormItem>

	<FormItem>
		<Checkbox label="Favorite" bind:checked={isFavorite} />
		<Checkbox label="To read" bind:checked={isToRead} />
		<Checkbox label="Archived" bind:checked={isArchived} />
	</FormItem>

	<FormItem>
		<Button type="submit">Save</Button>
		<Button on:click={handleClickCancel}>Cancel</Button>
		{#if canDelete}
			<Button on:click={handleClickDelete}>Delete</Button>
		{/if}
	</FormItem>
</form>

// src/components/BookmarkForm.vue
<template>
    <form v-on:submit="onSubmit">
        <div>
            <label for="url">Link</label>
            <input id="url" name="url" type="text" v-model="bookmark.url" />
        </div>
        
        <div>
            <label for="title">Title</label>
            <input id="title" name="title" type="text" v-model="bookmark.title" />
        </div>
        
        <div>
            <input id="isToRead" name="isToRead" type="checkbox" v-model="bookmark.isToRead" />
            <label for="isToRead">To read</label>
        </div>
        
        <div>
            <input id="isFavorite" name="isFavorite" type="checkbox" v-model="bookmark.isFavorite" />
            <label for="isFavorite">Favorite</label>
        </div>
        
        <div>
            <input id="isArchived" name="isArchived" type="checkbox" v-model="bookmark.isArchived" />
            <label for="isArchived">Archived</label>
        </div>
        
        <button type="submit">Add new bookmark</button>
        <button>Cancel</button>
        <button>Delete</button>
    </form>
</template>

<script>
    export default {
        props: ['bookmark', 'onSubmit'],
    }
</script>
