// src/components/BookmarkList.svelte
<script lang="ts">
	import type { Bookmark } from "./../store/bookmarks.js";
	import BookmarkItem from "./BookmarkItem.svelte";

	type SortingMethod = "date";
	export let bookmarks: Bookmark[] = [];
	export let sortedBy: SortingMethod = "date";

	$: sortedBookmarks = (() => {
		if (sortedBy === "date") {
			return [...bookmarks].sort((a, b) => b.dateCreated - a.dateCreated);
		}

		return bookmarks;
	})();
</script>

<ul>
	{#each sortedBookmarks as bookmark (bookmark.id)}
		<li>
			<BookmarkItem {bookmark} />
		</li>
	{/each}
</ul>

<style lang="scss">
	ul {
		list-style: none;
		padding-left: 0;
		margin: 0;
	}

	li + li {
		margin-top: 26px;
	}
</style>

// src/components/BookmarkList.vue
<template>
    <ul class="bookmark-list">
        <li
            class="bookmark-list__item"
            v-for="bookmark in bookmarks"
            :key="bookmark.id"
        >
            <bookmark-item :bookmark="bookmark"></bookmark-item>
        </li>
    </ul>
</template>

<script>
    import BookmarkItem from './BookmarkItem';
    
    export default {
        props: ['bookmarks'],
        components: {
            BookmarkItem
        }
    };
</script>

<style lang="scss">
    .bookmark-list {
        list-style: none;
    }
</style>
