// src/components/BookmarkItem.vue
<template>
	<li class="BookmarkItem">
		<Modal v-if="isEditing">
			<BookmarkForm
				:bookmark="bookmark"
				@submit="handleSubmitBookmarkForm(bookmark.id, $event)"
				@delete="handleDeleteBookmark(bookmark.id)"
				@cancel="isEditing = !isEditing"
			/>
		</Modal>

		<Button
			class="BookmarkItem__favorite"
			:class="{ 'is-favorite': bookmark.isFavorite }"
			variant="filled"
			color="transparent"
			size="small"
			@click="setBookmarkIsFavorite(bookmark.id, !bookmark.isFavorite)"
		>
			★
		</Button>

		<div class="BookmarkItem__title">
			<a
				v-if="bookmark.url"
				:href="bookmark.url"
				target="_blank"
				rel="noopener noreferrer"
				class="BookmarkItem__link"
			>
				{{ bookmark.title || bookmark.url }}
			</a>
			<span v-else>
				{{ bookmark.title || bookmark.url }}
			</span>
		</div>

		<Row class="BookmarkItem__actions">
			<Button
				@click="startEditing"
				variant="text"
				size="small"
			>
				edit
			</Button>

			<Button
				v-if="bookmark.isToRead"
				variant="text"
				size="small"
				@click="setBookmarkIsToRead(bookmark.id, false)"
			>
				mark as read
			</Button>

			<Button
				v-if="!bookmark.isArchived"
				variant="text"
				size="small"
				@click="setBookmarkIsArchived(bookmark.id, true)"
			>
				archive
			</Button>

			<Button
				v-if="bookmark.isArchived"
				variant="text"
				size="small"
				@click="setBookmarkIsArchived(bookmark.id, false)"
			>
				unarchive
			</Button>
		</Row>

		<TagList
			class="BookmarkItem__tags"
			:tags="bookmark.tags"
		/>
	</li>
</template>

<script>
	import Button from './Button.vue';
	import BookmarkForm from './BookmarkForm.vue';
	import Modal from './Modal.vue';
	import Row from './Row.vue';
	import TagList from './TagList.vue';

	export default {
		props: ['bookmark'],
		components: {
			BookmarkForm,
			Button,
			Modal,
			Row,
			TagList,
		},
		data: () => {
			return {
				isEditing: false,
			};
		},
		computed: {
			bookmarkSource() {
				return new URL(this.bookmark.url).hostname;
			}
		},
		methods: {
			startEditing() {
				this.isEditing = true;
			},
			handleSubmitBookmarkForm(id, bookmark) {
				this.updateBookmark(id, bookmark);
				this.isEditing = false;
			},
			handleDeleteBookmark(id) {
				this.deleteBookmark(id);
				this.isEditing = false;
			},
			updateBookmark(id, bookmark) {
				this.$store.dispatch('updateBookmark', { id, bookmark });
			},
			setBookmarkIsToRead(id, isToRead) {
				this.$store.dispatch('updateBookmark', { id, bookmark: { isToRead }});
			},
			setBookmarkIsFavorite(id, isFavorite) {
				this.$store.dispatch('updateBookmark', { id, bookmark: { isFavorite }});
			},
			setBookmarkIsArchived(id, isArchived) {
				this.$store.dispatch('updateBookmark', { id, bookmark: { isArchived }});
			},
			deleteBookmark(bookmarkId) {
				this.$store.dispatch('deleteBookmark', bookmarkId);
			},
		},
	}
</script>

<style lang="scss">
	.BookmarkItem + .BookmarkItem {
		margin-top: var(--baseline);
	}

	.BookmarkItem {
		display: grid;
		grid-template-columns: 26px 1fr;
		grid-template-rows: min-content min-content min-content;

		@media (min-width: 640px) {
			grid-template-columns: 26px 1fr max-content;
			grid-template-rows: min-content min-content;
		}
	}

	.BookmarkItem__title {
		grid-row: 1;
		grid-column: 2 / -1;
		line-height: var(--baseline);

		@media (min-width: 640px) {
			grid-column: 2 / 3;
		}
	}

	.BookmarkItem__link {
		color: #0044ab;
	}

	.BookmarkItem__actions {
		grid-row: 2;
		grid-column: 1 / -1;

		@media (min-width: 640px) {
			grid-row: 1;
			grid-column: 3;

			justify-content: flex-end;
			align-items: flex-start;
			margin-left: 25px;
		}
	}

	.BookmarkItem__tags {
		grid-row: 3;
		grid-column: 1 / -1;

		@media (min-width: 640px) {
			grid-row: 2 / 2;
			grid-column: 2 / -1;
		}
	}

	.BookmarkItem__favorite {
		grid-column: 1;
		grid-row: 1 / -1;
		display: flex;
		padding-left: 0;
		color: #ccc;
		font-size: 17px;

		&.is-favorite {
			color: gold;
		}
	}
</style>

// src/components/BookmarkItem.svelte
<script lang="ts">
	import { bookmarkBeingEdited, bookmarks } from "../store/bookmarks";
	import { entityBeingEdited } from "../store/ui.js";
	import ActionRow from "./ActionRow.svelte";
	import TagList from "./TagList.svelte";
	import type { Bookmark } from "../store/bookmarks";

	export let bookmark: Bookmark;

	$: actions = (() => {
		const actions = [];

		if (bookmark.isToRead) {
			actions.push({
				label: "mark as read",
				callback: markAsRead,
			});
		}

		if ($bookmarkBeingEdited?.id !== bookmark.id) {
			actions.push({
				label: "edit",
				callback: startEditing,
			});
		}

		return actions;
	})();

	function startEditing() {
		$entityBeingEdited = {
			type: "bookmark",
			id: bookmark.id,
		};
	}

	function markAsRead() {
		bookmarks.patch(bookmark.id, { isToRead: true });
	}

	function toggleIsFavorite() {
		bookmarks.patch(bookmark.id, { isFavorite: !bookmark.isFavorite });
	}
</script>

<div class="bookmark-item">
	<button
		on:click={toggleIsFavorite}
		class="button-toggle-favorite"
		class:is-favorite={bookmark.isFavorite}
		aria-label={bookmark.isFavorite
			? "Remove from favorites"
			: "Mark as favorite"}
	>
		{bookmark.isFavorite ? "★" : "☆"}
	</button>

	<h3 class="title" class:is-placeholder={!bookmark.url && !bookmark.title}>
		{#if bookmark.url.length > 0}
			<a
				class="link"
				href={bookmark.url}
				target="_blank"
				rel="noopener noreferrer"
			>
				{#if bookmark.title.length > 0}
					{bookmark.title}
				{:else}
					{bookmark.url}
				{/if}
			</a>
		{:else if bookmark.title}
			{bookmark.title}
		{:else}
			New bookmark
		{/if}
	</h3>

	<div class="actions">
		<ActionRow {actions} />
	</div>

	<div class="tags">
		{#if bookmark.tags.length > 0}
			<TagList tags={bookmark.tags} />
		{/if}
	</div>
</div>

<style lang="scss">
	.bookmark-item {
		display: grid;
		grid-template-columns: var(--baseline) 1fr;
		grid-template-rows: min-content min-content min-content;

		@media (min-width: 721px) {
			grid-template-columns: var(--baseline) 1fr max-content;
			grid-template-rows: min-content min-content;
		}
	}

	.title {
		grid-row: 1;
		grid-column: 2 / -1;
		overflow: hidden;
		text-overflow: ellipsis;
		font-size: 17px;
		font-weight: normal;
		line-height: var(--baseline);

		&.is-placeholder {
			color: var(--color-text-soft);
		}

		@media (min-width: 721px) {
			grid-column: 2 / 3;
		}
	}

	.actions {
		grid-row: 3;
		grid-column: 1 / -1;

		@media (min-width: 721px) {
			grid-row: 1;
			grid-column: 3;
			margin-left: 15px;
		}
	}

	.tags {
		grid-row: 2;
		grid-column: 1 / -1;

		@media (min-width: 721px) {
			grid-row: 2 / 2;
			grid-column: 2 / -1;
		}
	}

	.button-toggle-favorite {
		grid-column: 1;
		grid-row: 1;
		cursor: pointer;
		background-color: transparent;
		border: 0;
		font-size: 17px;
		height: var(--baseline);
		color: var(--color-text-soft);
		transition: 0.2s color;

		&.is-favorite,
		&:hover,
		&:focus-visible {
			color: #ff9b00;
		}
	}

	.link {
		color: var(--color-link);
	}
</style>
