// src/components/Button.vue
<template>
	<button
		class="Button"
		:class="{
			[`Button--size-${size}`]: true,
			[`Button--variant-${variant}`]: true,
			[`Button--color-${color}`]: true,
		}"
		:disabled="disabled"
		@click="$emit('click', $event)"
		:type="type"
	>
		<slot/>
	</button>
</template>

<script>
	export default {
		props: {
			disabled: {
				type: Boolean,
			},
			type: {
				type: String,
				default: 'button',
			},
			size: {
				type: String,
				default: 'normal',
			},
			variant: {
				type: String,
				default: 'outline',
			},
			color: {
				type: String,
				default: 'black',
			}
		},
	}
</script>

<style lang="scss">
	.Button {
		display: block;
		line-height: var(--baseline);
		font-size: var(--font-size-button);
		white-space: nowrap;
		background-color: transparent;
		border: 0;
		border-radius: 5px;

		&:not(:disabled) {
			cursor: pointer;
		}
	}

	.Button:disabled {
		opacity: 0.5;
	}

	.Button--color-transparent {
		--border-color-button: transparent;
		--background-color-button: transparent;
		--color-button: #ffffff;
	}

	.Button--color-black {
		--border-color-button: gray;
		--background-color-button: #000000;
		--color-button: #ffffff;
	}

	.Button--variant-filled,
	.Button--variant-outline {
		padding-right: var(--padding-button);
		padding-left: var(--padding-button);
	}

	.Button--variant-filled {
		background-color: var(--background-color-button);
		color: var(--color-button);
	}

	.Button--variant-outline {
		border: 1px solid var(--border-color-button);
		color: var(--background-color-button);
	}

	.Button--variant-text {
		&:hover,
		&:focus {
			text-decoration: underline;
		}
	}

	.Button--size-normal {
		--padding-button: 10px;
		--font-size-button: --font-size-body;
	}

	.Button--size-small {
		--padding-button: 5px;
		--font-size-button: 14px;
	}
</style>

// src/components/Button.svelte
<script lang="ts">
	export let disabled: boolean = false;
	export let type: "button" | "submit" = "button";
	export let variant: "outline" | "text" = "outline";
	export let size: "normal" | "small" = "normal";
</script>

<button
	on:click
	{type}
	{disabled}
	class:variant-outline={variant === "outline"}
	class:variant-text={variant === "text"}
	class:size-normal={size === "normal"}
	class:size-small={size === "small"}
>
	<slot />
</button>

<style lang="scss">
	button {
		--border-color-button: gray;
		--text-color-button: #000000;
		--color-button: #ffffff;

		display: inline-block;
		line-height: var(--baseline);
		white-space: nowrap;
		border: 0;
		background-color: transparent;
		color: var(--text-color-button);

		&:not(:disabled) {
			cursor: pointer;
		}
	}

	.variant-outline {
		padding: 0 10px;
		border-radius: 5px;
		border: 1px solid var(--border-color-button);
	}

	.variant-text {
		&:hover,
		&:focus {
			text-decoration: underline;
		}
	}

	.size-normal {
		font-size: 16px;
	}

	.size-small {
		font-size: 14px;
	}
</style>
