// src/pages/Login.svelte
<script lang="ts">
	import { auth } from "../utils/firebase";
	import { navigate } from "svelte-routing";
	import FormItem from "../components/form/FormItem.svelte";
	import InputPassword from "../components/form/InputPassword.svelte";
	import InputText from "../components/form/InputText.svelte";
	import Button from "../components/Button.svelte";
	import Page from "./Page.svelte";

	let emailAddress: string = "";
	let password: string = "";
	let isSubmitPending: boolean = false;
	let errors = [];

	async function handleSubmit() {
		isSubmitPending = true;
		errors = [];

		try {
			await auth.signInWithEmailAndPassword(emailAddress, password);
			isSubmitPending = false;
			console.log("success!");
			navigate("/");
		} catch (error) {
			if (error.code === "auth/invalid-email") {
				errors.push({
					field: "email",
					message: "The email address you provided is not valid.",
				});
			} else if (error.code === "auth/user-disabled") {
				errors.push({
					field: "email",
					message:
						"The user this email address belongs to has been disabled.",
				});
			} else if (error.code === "auth/user-not-found") {
				errors.push({
					field: "email",
					message:
						"No user exists for the email address you provided.",
				});
			} else if (error.code === "auth/wrong-password") {
				errors.push({
					field: "password",
					message: "The password is incorrect.",
				});
			} else {
				errors.push({
					isForForm: true,
					message: "Something went wrong. Please try again.",
				});
			}

			isSubmitPending = false;
		}
	}
</script>

<Page>
	<h1>Login</h1>

	<form on:submit|preventDefault={handleSubmit}>
		<FormItem label="Email address" labelFor="loginEmailAddress">
			<InputText
				type="email"
				bind:value={emailAddress}
				id="loginEmailAddress"
				autocomplete="username"
				required
				disabled={isSubmitPending}
			/>
		</FormItem>

		<FormItem label="Password" labelFor="loginPassword">
			<InputPassword
				bind:value={password}
				id="loginPassword"
				autocomplete="current-password"
				required
				disabled={isSubmitPending}
			/>
		</FormItem>

		<FormItem>
			<Button type="submit" disabled={isSubmitPending}>Log in</Button>
		</FormItem>
	</form>
</Page>

// src/components/Login.vue
<template>
	<div class="Login">
		<TopBar>
			<template v-slot:left>
				<h1 class="Login__title">
					Log in
				</h1>
			</template>
		</TopBar>

		<main>
			<form @submit.prevent="handleSubmitLogin">
				<FormError
					v-if="hasErrorForForm"
					class="Login__formError"
					:text="errorMessageForForm"
				/>

				<FormInput
					v-model:value="email"
					type="email"
					label="Email address"
					autocomplete="username"
					required
					:error="getErrorMessageForField('email')"
					@input="clearErrorForField('email')"
				/>

				<FormInput
					v-model:value="password"
					type="password"
					label="Password"
					autocomplete="new-password"
					required
					:error="getErrorMessageForField('password')"
					@input="clearErrorForField('password')"
				/>

				<FormItem>
					<Button
						:disabled="isSubmitPending"
						type="submit"
					>
						Log in
					</Button>
				</FormItem>
			</form>
		</main>
	</div>
</template>

<script>
	import Button from './Button.vue';
	import FormError from './FormError.vue';
	import FormInput from './FormInput.vue';
	import FormItem from './FormItem.vue';
	import TopBar from './TopBar.vue';
	import { auth } from './../utility/firebase.js';

	export default {
		components: {
			Button,
			FormError,
			FormInput,
			FormItem,
			TopBar,
		},
		data() {
			return {
				email: null,
				errors: [],
				password: null,
				isSubmitPending: false,
			};
		},
		computed: {
			hasErrorForForm() {
				return this.errors.some((error) => {
					return error.isForForm;
				});
			},
			errorMessageForForm() {
				const error = this.errors.find((error) => {
					return error.isForForm;
				});

				if (!error) {
					return null;
				}

				return error.message;
			}
		},
		methods: {
			clearErrors() {
				this.errors = [];
			},
			clearErrorForField(fieldName) {
				this.errors = this.errors.filter((error) => {
					error.field !== fieldName;
				});
			},
			hasErrorForField(fieldName) {
				return this.errors.some((error) => {
					return error.field === fieldName;
				});
			},
			getErrorMessageForField(fieldName) {
				const error = this.errors.find((error) => {
					return error.field === fieldName;
				});

				if (!error) {
					return null;
				}

				return error.message;
			},
			async handleSubmitLogin() {
				this.isSubmitPending = true;

				try {
					await auth.signInWithEmailAndPassword(this.email, this.password);
					this.isSubmitPending = false;
					this.$router.push('/');
				} catch(error) {
					if (error.code === 'auth/invalid-email') {
						this.errors.push({
							field: 'email',
							message: 'The email address you provided is not valid.'
						});
					} else if (error.code === 'auth/user-disabled') {
						this.errors.push({
							field: 'email',
							message: 'The user this email address belongs to has been disabled.',
						});
					} else if (error.code === 'auth/user-not-found') {
						this.errors.push({
							field: 'email',
							message: 'No user exists for the email address you provided.'
						});
					} else if (error.code === 'auth/wrong-password') {
						this.errors.push({
							field: 'password',
							message: 'The password is incorrect.'
						});
					} else {
						this.errors.push({
							isForForm: true,
							message: 'Something went wrong. Please try again.'
						});

						throw error;
					}

					this.isSubmitPending = false;
				}
			}
		}
	};
</script>

<style lang="scss">
	.Login__title {
		font-size: var(--font-size-body);
		line-height: calc(2 * var(--baseline));
	}

	.Login__formError {
		margin-bottom: 15px;
	}
</style>
