// src/components/Navigation.vue
<template>
	<nav class="Navigation">
		<NavigationSection title="Menu">
			<ul class="Navigation__list">
				<li
					v-if="$store.getters.isLoggedIn"
					class="Navigation__item"
				>
					<Button @click="handleClickLogout">Log out</Button>
				</li>

				<li
					v-if="!$store.getters.isLoggedIn"
					class="Navigation__item"
				>
					<router-link
						class="Navigation__link"
						to="/login"
						@click.native="$emit('close')"
					>
						Log in
					</router-link>
				</li>

				<li
					v-if="!$store.getters.isLoggedIn"
					class="Navigation__item"
				>
					<router-link
						class="Navigation__link"
						to="/signup"
						@click.native="$emit('close')"
					>
						Sign up
					</router-link>
				</li>
			</ul>
		</NavigationSection>

		<NavigationSection>
			<ul class="Navigation__list">
				<li
					v-for="(menuItem, index) in menuItems"
					class="Navigation__item"
					:key="index"
				>
					<router-link
						class="Navigation__link"
						:to="menuItem.route"
						@click.native="$emit('close')"
					>
						{{ menuItem.name }}
					</router-link>
				</li>
			</ul>
		</NavigationSection>

		<NavigationSection
			title="Lists"
			collapsible
		>
			<template v-slot:actions>
				<Button
					@click="handleClickCreateList"
					variant="text"
					size="small"
				>
					create
				</Button>
			</template>

			<ul class="Navigation__list" v-if="listMenuItems.length">
				<li
					class="Navigation__item Navigation__item--list"
					v-for="(listMenuItem, index) in listMenuItems"
					:key="index"
				>
					<router-link
						class="Navigation__link"
						:title="listMenuItem.name"
						:to="{
							name: 'list',
							params: { listId: listMenuItem.id }
						}"
						@click.native="$emit('close')"
					>
						{{ listMenuItem.name }}
					</router-link>

					<Row class="ListActions">
						<Button
							@click="handleClickEditList(listMenuItem.id)"
							size="small"
							variant="text"
						>
							edit
						</Button>
					</Row>
				</li>
			</ul>
		</NavigationSection>

		<NavigationSection
			v-if="Object.keys(orderedTagCount).length"
			title="Tags"
			collapsible
		>
			<ul class="Navigation__list">
				<li
					class="Navigation__item"
					v-for="([tag, amount], index) in Object.entries(orderedTagCount)"
					:key="index"
				>
					<router-link
						class="Navigation__link"
						:title="tag"
						:to="{
							name: 'tag',
							params: { tagName: tag }
						}"
						@click.native="$emit('close')"
					>
						{{ tag }}
					</router-link>

					<span class="TagCount">
						&middot; {{ amount }}
					</span>
				</li>
			</ul>
		</NavigationSection>

		<Modal v-if="isCreatingList">
			<ListForm
				@submit="handleSubmitNewList"
				@cancel="isCreatingList = false"
			/>
		</Modal>

		<Modal v-if="isEditingList && listToEdit">
			<ListForm
				:list="listToEdit"
				@submit="handleSubmitEditedList(listToEdit.id, $event)"
				@cancel="isEditingList = false"
				@delete="handleClickDeleteList(listToEdit.id)"
			/>
		</Modal>
	</nav>
</template>

<script>
	import Button from './Button.vue';
	import ListForm from './ListForm.vue';
	import Modal from './Modal.vue';
	import NavigationSection from './NavigationSection.vue';
	import Row from './Row.vue';
	import { auth } from './../utility/firebase.js';

	export default {
		components: {
			Button,
			ListForm,
			Modal,
			Row,
			NavigationSection,
		},
		data: function() {
			return {
				isCreatingList: false,
				isEditingList: false,
				listToEditId: null,
				menuItems: [
					{ name: 'Home', route: '/' },
					{ name: 'Read later', route: '/toread' },
					{ name: 'Favorites', route: '/favorites' },
					{ name: 'Archive', route: '/archive' },
				],
			};
		},
		computed: {
			listMenuItems() {
				return this.sortedLists.map(list => {
					return {
						id: list.id,
						name: list.title,
					};
				});
			},
			lists() {
				return this.$store.getters.allLists;
			},
			sortedLists() {
				return [...this.lists].sort((listA, listB) => {
					return listA.title - listB.title;
				})
			},
			listToEdit() {
				if (!this.listToEditId) {
					return null;
				}

				return this.$store.getters.listWithId(this.listToEditId);
			},
			tagCount() {
				return this.$store.getters.tagCount;
			},
			orderedTagCount() {
				const tagCount = this.tagCount;

				return Object.keys(tagCount).sort().reduce((orderedTagCount, tagName) => {
					return {
						...orderedTagCount,
						[tagName]: tagCount[tagName],
					}
				}, {});
			}
		},
		methods: {
			handleClickLogout() {
				auth.signOut();
			},
			handleClickCreateList() {
				this.$emit('close');
				this.isCreatingList = true;
			},
			handleClickEditList(listId) {
				this.listToEditId = listId;
				this.isEditingList = true;
			},
			handleSubmitNewList(list) {
				this.$store.dispatch('addList', list);
				this.isCreatingList = false;
			},
			handleSubmitEditedList(id, list) {
				this.$store.dispatch('updateList', { id, list });
				this.isEditingList = false;
			},
			handleClickDeleteList(listId) {
				this.$store.dispatch('deleteList', listId);
				this.isEditingList = false;
			},
		},
	};
</script>

<style lang="scss">
	.Navigation {
		overflow-y: scroll;
		height: 100%;
		padding-right: var(--gap);
		padding-left: var(--gap);
	}

	.Navigation__list {
		list-style: none;
		margin-bottom: var(--baseline);
	}

	.Navigation__item {
		display: flex;
		line-height: var(--baseline);
		white-space: nowrap;
	}

	.Navigation__item--list {
		justify-content: space-between;
	}

	.ListActions {
		margin-left: 6px;
	}

	.Navigation__link {
		display: inline;
		overflow: hidden;
		text-decoration: none;
		text-overflow: ellipsis;
		color: var(--color-text);

		&:hover,
		&:focus {
			text-decoration: underline;
		}

		&.router-link-exact-active {
			color: var(--color-highlight);
		}
	}

	.TagCount {
		margin-left: 6px;
		color: #aaa;
	}
</style>

// src/components/Navigation.svelte
<script lang="ts">
	import { navigate } from "svelte-routing";
	import { createNewFilterList, filterLists } from "../store/filters";
	import { localStore } from "../store/localStore";
	import { isLoggedIn } from "../store/session";
	import { doesTagMatchQuery, sortTagCount, tagCount } from "../store/tags";
	import {
		entityBeingEdited,
		showReadLaterCount,
		showTagCount,
		tagSortBy,
	} from "../store/ui";
	import { auth } from "../utils/firebase";
	import { sortObjects } from "../utils/sorting";
	import { bookmarksToRead } from "./../store/bookmarks";
	import ActionRow from "./ActionRow.svelte";
	import Button from "./Button.svelte";
	import InputText from "./form/InputText.svelte";
	import Select from "./form/Select.svelte";
	import NavigationItem from "./NavigationItem.svelte";
	import NavigationLink from "./NavigationLink.svelte";

	let tagSearchQuery: string = "";
	let isTagNavigationVisible = localStore("isTagNavigationVisible", true);
	let isFilterListNavigationVisible = localStore(
		"isListNavigationVisible",
		true
	);

	$: filterListActions = (() => {
		const actions: Array<{ label: string; callback: () => any }> = [
			{
				label: "create",
				callback: onClickCreateNewFilterList,
			},
		];

		if (sortedFilterLists.length > 0) {
			actions.push({
				label: $isFilterListNavigationVisible ? "hide" : "show",
				callback: toggleFilterListNavigationVisibility,
			});
		}

		return actions;
	})();

	$: tags = Object.entries($tagCount);
	$: filteredTags = tags.filter(([tagName]) => {
		return doesTagMatchQuery(tagName, tagSearchQuery);
	});
	$: sortedAndFilteredTags = sortTagCount(
		filteredTags,
		$tagSortBy,
		$tagSortBy === "name" ? "ascending" : "descending"
	);
	$: sortedFilterLists = sortObjects($filterLists, "title", "ascending");

	function logout() {
		auth.signOut();
	}

	function toggleTagNavigationVisibility() {
		$isTagNavigationVisible = !$isTagNavigationVisible;
	}

	function toggleFilterListNavigationVisibility() {
		$isFilterListNavigationVisible = !$isFilterListNavigationVisible;
	}

	function onClickCreateNewFilterList() {
		const newFilterList = createNewFilterList();
		filterLists.add(newFilterList);
		$entityBeingEdited = { type: "filterList", id: newFilterList.id };
		navigate(`/filter/${newFilterList.id}`);
	}
</script>

<nav>
	{#if !$isLoggedIn}
		<ul class="navigation__list">
			<NavigationItem on:navigate to="/login">Log in</NavigationItem>
			<NavigationItem on:navigate to="/signup">Sign up</NavigationItem>
		</ul>
	{/if}

	<ul class="navigation__list">
		<NavigationItem on:navigate to="/">Home</NavigationItem>
		<NavigationItem
			on:navigate
			to="/toread"
			count={$showReadLaterCount ? $bookmarksToRead.length : undefined}
		>
			Read later
		</NavigationItem>
		<NavigationItem on:navigate to="/favorites">Favorites</NavigationItem>
		<NavigationItem on:navigate to="/archive">Archive</NavigationItem>
	</ul>

	<header class="navigation__heading">
		<h2>Filters</h2>

		<ActionRow actions={filterListActions} />
	</header>

	{#if $isFilterListNavigationVisible && sortedFilterLists.length > 0}
		<ul class="navigation__list">
			{#each sortedFilterLists as filterList (filterList.id)}
				<NavigationItem on:navigate to={`/filter/${filterList.id}`}>
					{#if filterList.title}
						{filterList.title}
					{:else}
						New filter
					{/if}
				</NavigationItem>
			{/each}
		</ul>
	{/if}

	{#if tags.length > 0}
		<header class="navigation__heading">
			<h2>Tags</h2>

			<ActionRow
				actions={[
					{
						label: $isTagNavigationVisible ? "hide" : "show",
						callback: toggleTagNavigationVisibility,
					},
				]}
			/>
		</header>
	{/if}

	{#if tags.length > 0 && $isTagNavigationVisible}
		<div class="navigation__search">
			<InputText
				bind:value={tagSearchQuery}
				size="small"
				placeholder="Filter tags"
			/>
		</div>

		<small>
			<label for="tagSort">sort by</label>
			<Select
				id="tagSort"
				size="small"
				variant="text"
				options={[
					{ text: "name", value: "name" },
					{ text: "amount", value: "amount" },
				]}
				bind:value={$tagSortBy}
			/>
		</small>
	{/if}

	{#if sortedAndFilteredTags.length > 0 && $isTagNavigationVisible}
		<ul class="navigation__list">
			{#each sortedAndFilteredTags as [tagName, tagAmount] (tagName)}
				<NavigationItem
					on:navigate
					to={`/tag/${tagName}`}
					count={$showTagCount ? tagAmount : undefined}
				>
					{tagName}
				</NavigationItem>
			{/each}
		</ul>
	{:else if !!tagSearchQuery}
		<p>No tags found.</p>
	{/if}
</nav>

{#if $isLoggedIn}
	<footer class="navigation__footer">
		<NavigationLink to="settings" on:navigate>Settings</NavigationLink>
		<Button on:click={logout} variant="text">Log out</Button>
	</footer>
{/if}

<style lang="scss">
	nav {
		margin: var(--baseline);
	}

	.navigation__list {
		list-style: none;

		&:not(:first-child) {
			margin-top: var(--baseline);
		}
		&:not(:last-child) {
			margin-bottom: var(--baseline);
		}
	}

	.navigation__heading {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	.navigation__footer {
		display: flex;
		align-items: center;
		justify-content: space-between;
		position: sticky;
		bottom: 0;
		height: calc(2 * var(--baseline));
		padding-left: var(--baseline);
		padding-right: var(--baseline);
		border-top: 1px solid var(--border-color-ui-secondary);
		background-color: var(--background-color-ui-primary);
	}

	h2 {
		margin-bottom: 0;
	}
</style>
