// src/components/NavigationSection.vue
<template>
	<div class="NavigationSection">
		<header
			v-if="title || collapsible"
			class="NavigationSection__header"
		>
			<h2 class="NavigationSection__title">
				{{ title }}
			</h2>

			<Row class="NavigationSection__actions">
				<slot name="actions"/>

				<Button
					v-if="collapsible && $slots.default"
					variant="text"
					size="small"
					@click="isSectionHidden = !isSectionHidden"
				>
					{{ isSectionHidden ? 'show' : 'hide' }}
				</Button>
			</Row>
		</header>

		<div
			v-if="!isSectionHidden"
			class="NavigationSection__content"
		>
			<slot/>
		</div>
	</div>
</template>

<script>
	import Button from './Button.vue';
	import Row from './Row.vue';

	export default {
		components: {
			Button,
			Row,
		},
		props: {
			collapsible: {
				type: Boolean,
			},
			title: {
				type: String,
			},
		},
		data() {
			return {
				isSectionHidden: false,
			}
		},
	};
</script>

<style lang="scss">
	.NavigationSection__header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.NavigationSection__title {
		font-size: var(--font-size-body);
		line-height: calc(2 * var(--baseline));
	}
</style>

// src/components/NavigationSection.svelte
<script lang="ts">
	import ActionRow from "./ActionRow.svelte";

	export let title = "";
	export let actions = [];
	export let canCollapse = false;
	export let isCollapsed = false;

	$: sectionActions = (() => {
		if (!canCollapse || !$$slots.default) {
			return actions;
		}

		return [
			...actions,
			{
				label: isCollapsed ? "show" : "hide",
				callback: () => {
					isCollapsed = !isCollapsed;
				},
			},
		];
	})();
</script>

<section>
	{#if title || sectionActions}
		<header>
			<h2>{title}</h2>
			<ActionRow actions={sectionActions} />
		</header>
	{/if}

	<slot name="before" />

	{#if !isCollapsed}
		<ul>
			<slot />
		</ul>
	{/if}
</section>

<style lang="scss">
	section {
		margin-bottom: var(--baseline);
	}

	header {
		display: flex;
		justify-content: space-between;
	}

	h2 {
		margin-bottom: 0;
	}

	ul {
		list-style: none;
	}
</style>
