// src/components/Observer.svelte
<script lang="ts">
	import { createEventDispatcher, onMount } from "svelte";

	const dispatch = createEventDispatcher<{ intersect: undefined }>();
	export let rootMargin = "0px 0px 0px 0px";
	let element: HTMLDivElement;

	onMount(() => {
		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry && entry.isIntersecting) {
					dispatch("intersect");
				}
			},
			{ rootMargin }
		);

		observer.observe(element);

		return () => {
			observer.disconnect();
		};
	});
</script>

<div bind:this={element} />

// src/components/Observer.vue
<template>
	<div class="Observer"></div>
</template>

<script>
	export default {
		emits: ['intersect'],
		props: {
			rootMargin: {
				type: String,
				default: '0px 0px 0px 0px',
			},
		},
		data() {
			return {
				observer: null,
			};
		},
		mounted() {
			this.observer = new IntersectionObserver(([entry]) => {
				if (entry && entry.isIntersecting) {
					this.$emit('intersect');
				}
			});

			this.observer.observe(this.$el);
		},
		unmounted() {
			this.observer.disconnect();
		},
	}
</script>
