// src/components/SearchBar.svelte
<script lang="ts">
	import InputText from "./form/InputText.svelte";

	export let query: string;
</script>

<div class="search">
	<label class="search__label" for="local-search" aria-label="Search here">
		🔎
	</label>

	<InputText bind:value={query} id="local-search" />
</div>

<style lang="scss">
	.search {
		display: flex;
		align-items: center;
		margin-bottom: var(--baseline);
	}

	.search__label {
		font-size: 26px;
		width: 40px;
	}
</style>

// src/components/SearchBar.vue
<template>
	<div class="SearchBar">
		<span class="SearchBar__icon">🔎</span>

		<input
			class="SearchBar__input"
			:value="query"
			@input="$emit('update:query', $event.target.value)"
		/>
	</div>
</template>

<script>
	export default {
		props: {
			query: {
				type: String,
			},
		},
	};
</script>

<style lang="scss">
	.SearchBar {
		display: flex;
		align-items: center;
		margin-bottom: var(--baseline);
	}

	.SearchBar__icon {
		font-size: 26px;
		width: 40px;
	}

	.SearchBar__input {
		display: block;
		width: 100%;
		padding: 10px;
		font-size: var(--font-size-body);
		line-height: var(--baseline);
		border: 1px solid lightgray;
		border-radius: 5px;
	}
</style>
