// src/components/TagList.svelte
<script lang="ts">
	import { Link } from "svelte-routing";

	export let tags: string[];
</script>

<ul>
	{#each tags as tag}
		<li>
			<Link to={`/tag/${tag}`} class="taglist__link">
				{tag}
			</Link>
		</li>
	{/each}
</ul>

<style lang="scss">
	ul {
		display: flex;
		flex-wrap: wrap;
		list-style: none;
	}

	li {
		font-size: 14px;
		line-height: 26px;

		&:not(:last-child) {
			margin-right: 10px;
		}
	}

	:global(.taglist__link) {
		color: inherit;
	}
</style>

// src/components/TagList.vue
<template>
	<ul class="TagList" v-if="tags.length">
		<TagItem
			v-for="(tag, index) in tags"
			class="TagList__item"
			:key="index"
			:tag="tag"
		/>
	</ul>
</template>

<script>
	import TagItem from './TagItem';

	export default {
		props: {
			tags: {
				type: Array,
				default: () => [],
			},
		},
		components: {
			TagItem,
		},
	};
</script>

<style lang="scss">
	.TagList {
		display: flex;
		list-style: none;
		flex-wrap: wrap;
	}

	.TagList__item:not(:last-child) {
		margin-right: 10px;
	}
</style>
